name: tmdb_pilar
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  injectable: ^2.4.0
  get_it: ^7.6.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  injectable_generator: ^2.6.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.otf
        - asset: assets/fonts/SourceSansPro-BlackIt.otf
        - asset: assets/fonts/SourceSansPro-Bold.otf
        - asset: assets/fonts/SourceSansPro-BoldIt.otf
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
        - asset: assets/fonts/SourceSansPro-ExtraLightIt.otf
        - asset: assets/fonts/SourceSansPro-It.otf
        - asset: assets/fonts/SourceSansPro-Light.otf
        - asset: assets/fonts/SourceSansPro-LightIt.otf
        - asset: assets/fonts/SourceSansPro-Regular.otf
        - asset: assets/fonts/SourceSansPro-Semibold.otf
        - asset: assets/fonts/SourceSansPro-SemiboldIt.otf
